### ISSUE TITLE
Can you include a license for this project?

### ISSUE THREAD

**Issue by sona1111** [jaromvogel/ProcreateViewer#1]
@jaromvogel I really appreciate the effort that you put into this project. I was considering using a piece of the python file parser code in a tangentially related project, but as there is no license, I don't think I am legally allowed to do so. As sometimes folks don't realize that this is the case, I thought I would open an issue just to make you aware. Feel free to close it if you intend to reserve all rights. 

Thanks again!

**Comment by jaromvogel** [comment]
@sona1111 thanks for the reminder—I just added an MIT license to the project, hopefully that works for you!

**Comment by sona1111** [comment]
@jaromvogel Thank you very much! I will point you to the project as soon as it is open sourced and properly credit!
