### ISSUE TITLE
Could not find the download link

### ISSUE THREAD

**Issue by gitforziio** [jaromvogel/ProcreateViewer#2]
Hello! Thank you for providing this plugin!

But it seems that the download page is almost empty.
What I saw was like this:
<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/10508116/72865676-ac24fe80-3d13-11ea-8b9b-3e7b2b9ad1ce.png">

Was this a network problem or something else?

**Comment by jaromvogel** [comment]
That’s strange—I just checked the link and it’s working for me. You can also try downloading the latest version directly here: https://jaromvogel.com/ProcreateViewer.pkg

**Comment by gitforziio** [comment]
It works. Thanks lot!
